version: 2

sources:
  - name: dbt_circle_thomas
    description: dataset contenant les données sources de Circle
    database: weighty-flux-428109-e5    
    schema: dbt_circle_thomas          
    tables:
      - name: sales
        identifier: raw_cc_sales     
        description: table des ventes de Circle
        columns:
          - name: date_date
            description: les dates associées aux ventes de mes produits
          - name: product_id
            description: liste des products id vendus par Circle
          - name: quantity

  - name: gz_raw_data
    database: weighty-flux-428109-e5   
    schema: gz_raw_data                
    description: dataset exo jour 1
    config: 
      freshness: 
        error_after: {count: 12, period: hour}
        warn_after: {count: 24, period: day}
    tables:
      - name: sales
        identifier: raw_gz_sales       
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship
      - name: adwords
        identifier: raw_gz_adwords
      - name: facebook
        identifier: raw_gz_facebook
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo




models:
  - name: stock
    columns:
      - name: product_id_pk
        description: primary key product ID
        tests:
          - unique
          - not_null 
  - name: int_campaigns
    columns:
      - name: paid_source
        tests:
          - not_null
      - name: campaign_name
        tests:
          - not_null
    tests:
      - unique:
          column_name: "(campaign_key || '_' || date_date)"
  - name: finance_campaigns_month
    columns:
      - name: ads_margin
        description: ads margin calculation...

        
